name: "Build/Publish Container and Update tag as per package.json"

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push-container-image:

    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.head_commit.message, 'helmchart-version-change') }}

    env:
      CONTAINER_REGISTRY: docker.io
      CONTAINER_IMAGE: syamj/hello-kubernetes

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image and version variables
        run: |
          echo "IMAGE=$CONTAINER_REGISTRY/$CONTAINER_IMAGE" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$(cat src/app/package.json | jq -r .version)" >> $GITHUB_ENV
      

      - name: Build image
        run: | 
          docker build --tag "$IMAGE:$IMAGE_VERSION" \
            --build-arg IMAGE_VERSION="$IMAGE_VERSION" \
            --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" \
            --file src/app/Dockerfile src/app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image and tags to registry
        run: |
          docker push $IMAGE:$IMAGE_VERSION
      - name: Update chart
        run: |
          sed -i "6s/.*/appVersion: $IMAGE_VERSION/" deploy/Chart.yaml
          git config --local user.name "syamj"
          git add deploy/Chart.yaml
          git commit -m "helmchart-version-change"
      - name: push changed to helm 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
